version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bingchat
      - POSTGRES_DB=bingchat
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: chatapi-db